version: "3.7"

services:
  api:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017/fruits
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - ./.devcontainer/.vscode:/api/.vscode
      - ~/.ssh/:/opt/odoo/.ssh/
    ports: ["3000:3000"]

  mongo:
    image: mongo
